### ISSUE TITLE
代码的引号好像不对

### ISSUE THREAD

**Issue by KLdivergence** [phodal/github#17]
License 使用情况

又比如，在我们看到的一些外版书籍上，如果拥有代码。那么作者一般就会在前言或者类似的位置里，指明书中代码的版权所属。如：``也许你需要在自己的程序或文档中用到本书的代码，但除非大篇幅地使用，否则不必与我们联系取得授权。例如，用本书中的几段代码编写程序无需请求许可，blabla。``

**Comment by phodal** [comment]
@KLdivergence 3q
