### ISSUE TITLE
I cant read chinese

### ISSUE THREAD

**Issue by pizzastar** [phodal/github#26]
Help

**Comment by UpcraftLP** [comment]
[This](https://www.google.com/search?q=google%20translate%20chinese "Chinese") will help you ;)

**Comment by phodal** [comment]
Hello, I'm sorry about it. When I create this job, I hope it can help Chinese guys to do better in GitHub. And at the time, there are a lot of tutorials in English.

**Comment by UpcraftLP** [comment]
@phodal dw, that guy is a troll... just look at their github activity..

**Comment by phodal** [comment]
@UpcraftLP It's fine. This repo is prepare for new user in GitHub.

 But I can close this issue, 😆
