### ISSUE TITLE
pdf format issue

### ISSUE THREAD

**Issue by jiangnanhugo** [phodal/github#29]
the generated pdf file contains issue on formatting codes and tables, part of the codes and string in tables are displayed outside the pages.

**Comment by phodal** [comment]
@jiangnanhugo it's a Latex issue, trying to fixed it.

**Comment by codeAPTX4869** [comment]
@jiangnanhugo what happen?

**Comment by krishnakakade1999** [comment]
@jiangnanhugo just i checked that file(.pdf) that file showing a content but that is in chinese language i think that issue is solved but new issue is ``put" <b> upload that pdf in english language</b>

**Comment by cuadrosarte100** [comment]
Okay
