### ISSUE TITLE
Suggestion: Add a sidebar list or a back to top button？

### ISSUE THREAD

**Issue by darkSheep404** [phodal/github#51]
在这个网站拜读大大的博客[GitHub 漫游指南](http://github.phodal.com/#git-%E5%9F%BA%E6%9C%AC%E7%9F%A5%E8%AF%86%E4%B8%8E-github-%E4%BD%BF%E7%94%A8)
有一些阅读体验上的感想
* 对这样一篇长文来说，没有侧边目录或者回到顶部按钮的阅读稍显困难
* 顶部目录的字体和颜色也不是很显眼
大大是否会考虑进行一些阅读体验上的优化呢？
最后，对大大无私分享的知识表示感谢

**Comment by phodal** [comment]
会……，考虑了很多，但是没时间改。

**Comment by phodal** [comment]
done in #68

**Comment by darkSheep404** [comment]
> done in #68

by the way,i'm the boy recognized you in teacher introduction the bootcamp that just ended last week😬
what a coincidence!🥳

**Comment by phodal** [comment]
哈哈，两年了，我在挖新的坑，一直没管。结果有人修了
