### ISSUE TITLE
一些小错误及建议

### ISSUE THREAD

**Issue by PDPENG** [phodal/github#66]
## error
**部分标题格式未渲染，少空格**

![](https://cdn.jsdelivr.net/gh/PDPENG/jason-storage/blog-img/20220215131211.png)

![](https://cdn.jsdelivr.net/gh/PDPENG/jason-storage/blog-img/github-wander-error2.jpg)

**一些图片无法加载**

![](https://cdn.jsdelivr.net/gh/PDPENG/jason-storage/blog-img/github-wander-error3.jpg)

## 更新建议
在拜读大佬的文章时，网页浏览的页面要是能有一个**侧边栏显示目录**或者在标题位置加上**锚点**，更能提升阅读体验，免去每次打开重新定位的操作

**Comment by PDPENG** [comment]
好的，支持ing！

**Comment by PDPENG** [comment]
在线阅读`开源项目维护` 位置是缺少了什么嘛，感觉没有写完的样子（先记录下，尝试pr中……）

**Comment by PDPENG** [comment]
> 在线阅读`开源项目维护` 位置是缺少了什么嘛，感觉没有写完的样子（先记录下，尝试pr中……）

此处不了解坐着想表达的含义（是不是少了超链接？），未做任何修改

**Comment by phodal** [comment]
我估计是需要删了的

**Comment by PDPENG** [comment]
哈哈，好的

**Comment by PDPENG** [comment]
看完之后也是完成了我的第一个 PR 呀，感谢作者，[总结一下](https://dp-json.blog.csdn.net/article/details/123053996)
